// Appearance
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

// Auth
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// Checklist
//Create Template
export const POST_CHECKLIST_TEMPLATE_START = 'POST_CHECKLIST_TEMPLATE_START';
export const POST_CHECKLIST_TEMPLATE_SUCCESS = 'POST_CHECKLIST_TEMPLATE_SUCCESS';
export const POST_CHECKLIST_TEMPLATE_FAIL = 'POST_CHECKLIST_TEMPLATE_FAIL';

//Update Template
export const UPDATE_CHECKLIST_TEMPLATE_START = 'UPDATE_CHECKLIST_TEMPLATE_START';
export const UPDATE_CHECKLIST_TEMPLATE_SUCCESS = 'UPDATE_CHECKLIST_TEMPLATE_SUCCESS';
export const UPDATE_CHECKLIST_TEMPLATE_FAIL = 'UPDATE_CHECKLIST_TEMPLATE_FAIL';

//Get Checklist List
export const GET_CHECKLISTS_START = 'GET_CHECKLISTS_START';
export const GET_CHECKLISTS_SUCCESS = 'GET_CHECKLISTS_SUCCESS';
export const GET_CHECKLISTS_FAIL = 'GET_CHECKLISTS_FAIL';

//Get Checklist Template List
export const GET_CHECKLIST_TEMPLATE_LIST_START = 'GET_CHECKLIST_TEMPLATE_LIST_START';
export const GET_CHECKLIST_TEMPLATE_LIST_SUCCESS = 'GET_CHECKLIST_TEMPLATE_LIST_SUCCESS';
export const GET_CHECKLIST_TEMPLATE_LIST_FAIL = 'GET_CHECKLIST_TEMPLATE_LIST_FAIL';

//Delete Checklist
export const DELETE_CHECKLIST_START = 'DELETE_CHECKLIST_START';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const DELETE_CHECKLIST_FAIL = 'DELETE_CHECKLIST_FAIL';

//Get Single Checklist
export const GET_SINGLE_CHECKLIST_START = 'GET_SINGLE_CHECKLIST_START';
export const GET_SINGLE_CHECKLIST_SUCCESS = 'GET_SINGLE_CHECKLIST_SUCCESS';
export const GET_SINGLE_CHECKLIST_FAIL = 'GET_SINGLE_CHECKLIST_FAIL';

//Fill Checklist
export const POST_CHECKLIST_ENTRIES_START = 'POST_CHECKLIST_ENTRIES_START';
export const POST_CHECKLIST_ENTRIES_SUCCESS = 'POST_CHECKLIST_ENTRIES_SUCCESS';
export const POST_CHECKLIST_ENTRIES_FAIL = 'POST_CHECKLIST_ENTRIES_FAIL';

// Campaign
export const GET_CAMPAIGNS_LIST_START = 'GET_CAMPAIGNS_LIST_START';
export const GET_CAMPAIGNS_LIST_SUCCESS = 'GET_CAMPAIGNS_LIST_SUCCESS';
export const GET_CAMPAIGNS_LIST_FAIL = 'GET_CAMPAIGNS_LIST_FAIL';

// Current Campaign
export const GET_CURRENT_CAMPAIGN_START = 'GET_CURRENT_CAMPAIGN_START';
export const GET_CURRENT_CAMPAIGN_SUCCESS = 'GET_CURRENT_CAMPAIGN_SUCCESS';
export const GET_CURRENT_CAMPAIGN_FAIL = 'GET_CURRENT_CAMPAIGN_FAIL';

// Supplier List
export const GET_SUPPLIERS_STATIC_LIST_START = 'GET_SUPPLIERS_STATIC_LIST_START';
export const GET_SUPPLIERS_STATIC_LIST_SUCCESS = 'GET_SUPPLIERS_STATIC_LIST_SUCCESS';
export const GET_SUPPLIERS_STATIC_LIST_FAIL = 'GET_SUPPLIERS_STATIC_LIST_FAIL';

// Current Supplier
export const GET_CURRENT_STATIC_SUPPLIER_START = 'GET_CURRENT_STATIC_SUPPLIER_START';
export const GET_CURRENT_STATIC_SUPPLIER_SUCCESS = 'GET_CURRENT_STATIC_SUPPLIER_SUCCESS';
export const GET_CURRENT_STATIC_SUPPLIER_FAIL = 'GET_CURRENT_STATIC_SUPPLIER_FAIL';

//Post Supplier Type
export const POST_SUPPLIER_TYPE_START = 'POST_SUPPLIER_TYPE_START';
export const POST_SUPPLIER_TYPE_SUCCESS = 'POST_SUPPLIER_TYPE_SUCCESS';
export const POST_SUPPLIER_TYPE_FAIL = 'POST_SUPPLIER_TYPE_FAIL';

//Post Supplier
export const POST_SUPPLIER_START = 'POST_SUPPLIER_START';
export const POST_SUPPLIER_SUCCESS = 'POST_SUPPLIER_SUCCESS';
export const POST_SUPPLIER_FAIL = 'POST_SUPPLIER_FAIL';

//Get Supplier Type List
export const GET_SUPPLIER_TYPE_LIST_START = 'GET_SUPPLIER_TYPE_LIST_START';
export const GET_SUPPLIER_TYPE_LIST_SUCCESS = 'GET_SUPPLIER_TYPE_LIST_SUCCESS';
export const GET_SUPPLIER_TYPE_LIST_FAIL = 'GET_SUPPLIER_TYPE_LIST_FAIL';

//Get Supplier Type
export const GET_CURRENT_SUPPLIER_TYPE_START = 'GET_CURRENT_SUPPLIER_TYPE_START';
export const GET_CURRENT_SUPPLIER_TYPE_SUCCESS = 'GET_CURRENT_SUPPLIER_TYPE_SUCCESS';
export const GET_CURRENT_SUPPLIER_TYPE_FAIL = 'GET_CURRENT_SUPPLIER_TYPE_FAIL';

//Post Base Supplier Type
export const POST_BASE_SUPPLIER_TYPE_START = 'POST_BASE_SUPPLIER_TYPE_START';
export const POST_BASE_SUPPLIER_TYPE_SUCCESS = 'POST_BASE_SUPPLIER_TYPE_SUCCESS';
export const POST_BASE_SUPPLIER_TYPE_FAIL = 'POST_BASE_SUPPLIER_TYPE_FAIL';

//Get Base Supplier Type List
export const GET_BASE_SUPPLIER_TYPE_LIST_START = 'GET_BASE_SUPPLIER_TYPE_LIST_START';
export const GET_BASE_SUPPLIER_TYPE_LIST_SUCCESS = 'GET_BASE_SUPPLIER_TYPE_LIST_SUCCESS';
export const GET_BASE_SUPPLIER_TYPE_LIST_FAIL = 'GET_BASE_SUPPLIER_TYPE_LIST_FAIL';

//Get Base Supplier Type
export const GET_CURRENT_BASE_SUPPLIER_TYPE_START = 'GET_CURRENT_BASE_SUPPLIER_TYPE_START';
export const GET_CURRENT_BASE_SUPPLIER_TYPE_SUCCESS = 'GET_CURRENT_BASE_SUPPLIER_TYPE_SUCCESS';
export const GET_CURRENT_BASE_SUPPLIER_TYPE_FAIL = 'GET_CURRENT_BASE_SUPPLIER_TYPE_FAIL';

//Get Supplier
export const GET_CURRENT_SUPPLIER_START = 'GET_CURRENT_SUPPLIER_START';
export const GET_CURRENT_SUPPLIER_SUCCESS = 'GET_CURRENT_SUPPLIER_SUCCESS';
export const GET_CURRENT_SUPPLIER_FAIL = 'GET_CURRENT_SUPPLIER_FAIL';

//Get Supplier List
export const GET_SUPPLIER_LIST_START = 'GET_SUPPLIER_LIST_START';
export const GET_SUPPLIER_LIST_SUCCESS = 'GET_SUPPLIER_LIST_SUCCESS';
export const GET_SUPPLIER_LIST_FAIL = 'GET_SUPPLIER_LIST_FAIL';

//Get Permission List
export const GET_PERMISSION_LIST_START = 'GET_PERMISSION_LIST_START';
export const GET_PERMISSION_LIST_SUCCESS = 'GET_PERMISSION_LIST_SUCCESS';
export const GET_PERMISSION_LIST_FAIL = 'GET_PERMISSION_LIST_FAIL';

//Get User Permission
export const GET_USER_PERMISSION_START = 'GET_USER_PERMISSION_START';
export const GET_USER_PERMISSION_SUCCESS = 'GET_USER_PERMISSION_SUCCESS';
export const GET_USER_PERMISSION_FAIL = 'GET_USER_PERMISSION_FAIL';

// User List
export const GET_USERS_LIST_START = 'GET_USERS_LIST_START';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';

// Current User
export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';

// User Profile List
export const GET_USER_PROFILE_LIST_START = 'GET_USER_PROFILE_LIST_START';
export const GET_USER_PROFILE_LIST_SUCCESS = 'GET_USER_PROFILE_LIST_SUCCESS';
export const GET_USER_PROFILE_LIST_FAIL = 'GET_USER_PROFILE_LIST_FAIL';

// Get Lead Permission List
export const GET_LEAD_PERMISSION_LIST_START = 'GET_LEAD_PERMISSION_LIST_START';
export const GET_LEAD_PERMISSION_LIST_SUCCESS = 'GET_LEAD_PERMISSION_LIST_SUCCESS';
export const GET_LEAD_PERMISSION_LIST_FAIL = 'GET_LEAD_PERMISSION_LIST_FAIL';

//Get Lead User Permission
export const GET_LEAD_USER_PROFILE_PERMISSION_START = 'GET_LEAD_USER_PROFILE_PERMISSION_START';
export const GET_LEAD_USER_PROFILE_PERMISSION_SUCCESS = 'GET_LEAD_USER_PROFILE_PERMISSION_SUCCESS';
export const GET_LEAD_USER_PROFILE_PERMISSION_FAIL = 'GET_LEAD_USER_PROFILE_PERMISSION_FAIL';

//Get Logged In User Permission
export const GET_LOGGED_IN_USER_PERMISSION_START = 'GET_LOGGED_IN_USER_PERMISSION_START';
export const GET_LOGGED_IN_USER_PERMISSION_SUCCESS = 'GET_LOGGED_IN_USER_PERMISSION_SUCCESS';
export const GET_LOGGED_IN_USER_PERMISSION_FAIL = 'GET_LOGGED_IN_USER_PERMISSION_FAIL';

//Post Base Inventory
export const POST_BASE_INVENTORY_START = 'POST_BASE_INVENTORY_START';
export const POST_BASE_INVENTORY_SUCCESS = 'POST_BASE_INVENTORY_SUCCESS';
export const POST_BASE_INVENTORY_FAIL = 'POST_BASE_INVENTORY_FAIL';

// GET Base Inventory
export const GET_BASE_INVENTORY_START = 'GET_BASE_INVENTORY_START';
export const GET_BASE_INVENTORY_SUCCESS = 'GET_BASE_INVENTORY_SUCCESS';
export const GET_BASE_INVENTORY_FAIL = 'GET_BASE_INVENTORY_FAIL';

// DELETE Base Inventory
export const DELETE_BASE_INVENTORY_START = 'DELETE_BASE_INVENTORY_START';
export const DELETE_BASE_INVENTORY_SUCCESS = 'DELETE_BASE_INVENTORY_SUCCESS';
export const DELETE_BASE_INVENTORY_FAIL = 'DELETE_BASE_INVENTORY_FAIL';

// GET Base Inventory By ID
export const GET_BASE_INVENTORY_BY_ID_START = 'GET_BASE_INVENTORY_BY_ID_START';
export const GET_BASE_INVENTORY_BY_ID_SUCCESS = 'GET_BASE_INVENTORY_BY_ID_SUCCESS';
export const GET_BASE_INVENTORY_BY_ID_FAIL = 'GET_BASE_INVENTORY_BY_ID_FAIL';

// PUT Base Inventory
export const PUT_BASE_INVENTORY_START = 'PUT_BASE_INVENTORY_START';
export const PUT_BASE_INVENTORY_SUCCESS = 'PUT_BASE_INVENTORY_SUCCESS';
export const PUT_BASE_INVENTORY_FAIL = 'PUT_BASE_INVENTORY_FAIL';

// GET Inventory List
export const GET_INVENTORY_LIST_SUCCESS = 'GET_INVENTORY_LIST_SUCCESS';
export const GET_INVENTORY_LIST_FAIL = 'GET_INVENTORY_LIST_FAIL';

// POST Inventory
export const POST_INVENTORY_START = 'POST_INVENTORY_START';
export const POST_INVENTORY_SUCCESS = 'POST_INVENTORY_SUCCESS';
export const POST_INVENTORY_FAIL = 'POST_INVENTORY_FAIL';

// PUT Inventory
export const PUT_INVENTORY_START = 'PUT_INVENTORY_START';
export const PUT_INVENTORY_SUCCESS = 'PUT_INVENTORY_SUCCESS';
export const PUT_INVENTORY_FAIL = 'PUT_INVENTORY_FAIL';

// DELETE Inventory
export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS';
export const DELETE_INVENTORY_FAIL = 'DELETE_INVENTORY_FAIL';

//Delete Supplier Type
export const DELETE_SUPPLIER_TYPE_START = 'DELETE_SUPPLIER_TYPE_START';
export const DELETE_SUPPLIER_TYPE_SUCCESS = 'DELETE_SUPPLIER_TYPE_SUCCESS';
export const DELETE_SUPPLIER_TYPE_FAIL = 'DELETE_SUPPLIER_TYPE_FAIL';

//Delete Base Supplier Type
export const DELETE_BASE_SUPPLIER_TYPE_START = 'DELETE_BASE_SUPPLIER_TYPE_START';
export const DELETE_BASE_SUPPLIER_TYPE_SUCCESS = 'DELETE_BASE_SUPPLIER_TYPE_SUCCESS';
export const DELETE_BASE_SUPPLIER_TYPE_FAIL = 'DELETE_BASE_SUPPLIER_TYPE_FAIL';

//Delete Supplier
export const DELETE_SUPPLIER_START = 'DELETE_SUPPLIER_START';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL';

//campaigns form list
export const GET_CAMPAIGNS_FORM_LIST_START = 'GET_CAMPAIGNS_FORM_LIST_START';
export const GET_CAMPAIGNS_FORM_LIST_SUCCESS = 'GET_CAMPAIGNS_FORM_LIST_SUCCESS';
export const GET_CAMPAIGNS_FORM_LIST_FAIL = 'GET_CAMPAIGNS_FORM_LIST_FAIL';

//campaigns create lead form
export const POST_LEAD_FORM_START = 'POST_LEAD_FORM_START';
export const POST_LEAD_FORM_SUCCESS = 'POST_LEAD_FORM_SUCCESS';
export const POST_LEAD_FORM_FAIL = 'POST_LEAD_FORM_FAIL';

//campaigns get lead form
export const GET_LEAD_FORM_START = 'GET_LEAD_FORM_START';
export const GET_LEAD_FORM_SUCCESS = 'GET_LEAD_FORM_SUCCESS';
export const GET_LEAD_FORM_FAIL = 'GET_LEAD_FORM_FAIL';
// Base Booking
export const POST_BASE_BOOKING_START = 'POST_BASE_BOOKING_START';
export const POST_BASE_BOOKING_SUCCESS = 'POST_BASE_BOOKING_SUCCESS';
export const POST_BASE_BOOKING_FAIL = 'POST_BASE_BOOKING_FAIL';
export const PUT_BASE_BOOKING_START = 'PUT_BASE_BOOKING_START';
export const PUT_BASE_BOOKING_SUCCESS = 'PUT_BASE_BOOKING_SUCCESS';
export const PUT_BASE_BOOKING_FAIL = 'PUT_BASE_BOOKING_FAIL';
export const GET_BASE_BOOKING_LIST_START = 'GET_BASE_BOOKING_LIST_START';
export const GET_BASE_BOOKING_LIST_SUCCESS = 'GET_BASE_BOOKING_LIST_SUCCESS';
export const GET_BASE_BOOKING_LIST_FAIL = 'GET_BASE_BOOKING_LIST_FAIL';
export const DELETE_BASE_BOOKING_START = 'DELETE_BASE_BOOKING_START';
export const DELETE_BASE_BOOKING_SUCCESS = 'DELETE_BASE_BOOKING_SUCCESS';
export const DELETE_BASE_BOOKING_FAIL = 'DELETE_BASE_BOOKING_FAIL';
export const GET_BOOKING_TEMPLATE_LIST_START = 'GET_BOOKING_TEMPLATE_LIST_START';
export const GET_BOOKING_TEMPLATE_LIST_SUCCESS = 'GET_BOOKING_TEMPLATE_LIST_SUCCESS';
export const GET_BOOKING_TEMPLATE_LIST_FAIL = 'GET_BOOKING_TEMPLATE_LIST_FAIL';
export const POST_BOOKING_TEMPLATE_START = 'POST_BOOKING_TEMPLATE_START';
export const POST_BOOKING_TEMPLATE_SUCCESS = 'POST_BOOKING_TEMPLATE_SUCCESS';
export const POST_BOOKING_TEMPLATE_FAIL = 'POST_BOOKING_TEMPLATE_FAIL';
export const PUT_BOOKING_TEMPLATE_START = 'PUT_BOOKING_TEMPLATE_START';
export const PUT_BOOKING_TEMPLATE_SUCCESS = 'PUT_BOOKING_TEMPLATE_SUCCESS';
export const PUT_BOOKING_TEMPLATE_FAIL = 'PUT_BOOKING_TEMPLATE_FAIL';
export const DELETE_BOOKING_TEMPLATE_START = 'DELETE_BOOKING_TEMPLATE_START';
export const DELETE_BOOKING_TEMPLATE_SUCCESS = 'DELETE_BOOKING_TEMPLATE_SUCCESS';
export const DELETE_BOOKING_TEMPLATE_FAIL = 'DELETE_BOOKING_TEMPLATE_FAIL';

// Booking
export const GET_BOOKING_START = 'GET_BOOKING_START';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';
export const POST_BOOKING_START = 'POST_BOOKING_START';
export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS';
export const POST_BOOKING_FAIL = 'POST_BOOKING_FAIL';
export const PUT_BOOKING_START = 'PUT_BOOKING_START';
export const PUT_BOOKING_SUCCESS = 'PUT_BOOKING_SUCCESS';
export const PUT_BOOKING_FAIL = 'PUT_BOOKING_FAIL';
export const DELETE_BOOKING_START = 'DELETE_BOOKING_START';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL';
export const GET_CAMPAIGN_INVENTORY_START = 'GET_CAMPAIGN_INVENTORY_START';
export const GET_CAMPAIGN_INVENTORY_SUCCESS = 'GET_CAMPAIGN_INVENTORY_SUCCESS';
export const GET_CAMPAIGN_INVENTORY_FAIL = 'GET_CAMPAIGN_INVENTORY_FAIL';
export const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPLOAD_HASHTAG_IMAGE_START = 'UPLOAD_HASHTAG_IMAGE_START';
export const UPLOAD_HASHTAG_IMAGE_SUCCESS = 'UPLOAD_HASHTAG_IMAGE_SUCCESS';
export const UPLOAD_HASHTAG_IMAGE_FAIL = 'UPLOAD_HASHTAG_IMAGE_FAIL';

// Assignment
export const POST_ASSIGNMENT_START = 'POST_ASSIGNMENT_START';
export const POST_ASSIGNMENT_SUCCESS = 'POST_ASSIGNMENT_SUCCESS';
export const POST_ASSIGNMENT_FAIL = 'POST_ASSIGNMENT_FAIL';
export const GET_ASSIGNMENT_START = 'GET_ASSIGNMENT_START';
export const GET_ASSIGNMENT_SUCCESS = 'GET_ASSIGNMENT_SUCCESS';
export const GET_ASSIGNMENT_FAIL = 'GET_ASSIGNMENT_FAIL';
export const PUT_ASSIGNMENT_START = 'PUT_ASSIGNMENT_START';
export const PUT_ASSIGNMENT_SUCCESS = 'PUT_ASSIGNMENT_SUCCESS';
export const PUT_ASSIGNMENT_FAIL = 'PUT_ASSIGNMENT_FAIL';

// Phase
export const GET_PHASE_LIST_START = 'GET_PHASE_LIST_START';
export const GET_PHASE_LIST_SUCCESS = 'GET_PHASE_LIST_SUCCESS';
export const GET_PHASE_LIST_FAIL = 'GET_PHASE_LIST_FAIL';
export const POST_PHASE_START = 'POST_PHASE_START';
export const POST_PHASE_SUCCESS = 'POST_PHASE_SUCCESS';
export const POST_PHASE_FAIL = 'POST_PHASE_FAIL';
export const DELETE_PHASE_START = 'DELETE_PHASE_START';
export const DELETE_PHASE_SUCCESS = 'DELETE_PHASE_SUCCESS';
export const DELETE_PHASE_FAIL = 'DELETE_PHASE_FAIL';

//STATES
export const GET_STATES_START = 'GET_STATES_START';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';

//CITIES
export const GET_CITIES_START = 'GET_CITIES_START';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';

//AREAS
export const GET_AREAS_START = 'GET_AREAS_START';
export const GET_AREAS_SUCCESS = 'GET_AREAS_SUCCESS';
export const GET_AREAS_FAIL = 'GET_AREAS_FAIL';

//SUBAREAS
export const GET_SUBAREAS_START = 'GET_SUBAREAS_START';
export const GET_SUBAREAS_SUCCESS = 'GET_SUBAREAS_SUCCESS';
export const GET_SUBAREAS_FAIL = 'GET_SUBAREAS_FAIL';
